### ISSUE TITLE
SyntaxError: Unexpected token in LineChart/index.tsx and PieChart/index.tsx

### ISSUE THREAD

**Issue by imeidopf** [Abhinandan-Kushwaha/react-native-gifted-charts#342]
I'm working on just the basic Line Chart setup and upon compiling the code, I get some errors. Here is my JSX:

`import { Component, createElement } from "react";
import { View } from "react-native";
import { LineChart } from "react-native-gifted-charts";

import { mergeNativeStyles } from "@mendix/pluggable-widgets-tools";

const defaultStyle = {
    container: {},
    label: {
        color: "#F6BB42"
    }
};

export class HelloWorld extends Component {
    styles = mergeNativeStyles(defaultStyle, this.props.style);

    data = [
        { value: 15, label: 'A', labelComponent: () => null },
        { value: 30, label: 'B', labelComponent: () => null },
        { value: 26, label: 'C', labelComponent: () => null },
        { value: 40, label: 'D', labelComponent: () => null },
      ];

    render() {
        return (
            <View style={this.styles.container}>
                <LineChart
                    data={data}
                    height={250}
                    showVerticalLines
                    spacing={44}
                    initialSpacing={0}
                    color1="skyblue"
                    color2="orange"
                    textColor1="green"
                    dataPointsHeight={6}
                    dataPointsWidth={6}
                    dataPointsColor1="blue"
                    dataPointsColor2="red"
                    textShiftY={-2}
                    textShiftX={-5}
                    textFontSize={13}
                />
            </View>
        );
    }
}'

Here is the error:

`bundles C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\src\ReactNativeGiftedChartsLine.jsx → dist/tmp/widgets/kinetechcloud/reactnativegiftedchartsline/ReactNativeGiftedChartsLine.ios.js...
[!] (plugin commonjs--resolver) SyntaxError: Unexpected token (34:5) in C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\react-native-gifted-charts\src\LineChart\index.tsx
node_modules/react-native-gifted-charts/src/LineChart/index.tsx (34:5)
32: let animations = [];
33: 
34: type propTypes = {
         ^
35:   height?: number;
36:   noOfSections?: number;
SyntaxError: Unexpected token (34:5) in C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\react-native-gifted-charts\src\LineChart\index.tsx
    at Parser.pp$4.raise (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:19551:13)
    at Parser.pp$9.unexpected (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:16845:8)
    at Parser.pp$9.semicolon (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:16822:66)
    at Parser.pp$8.parseExpressionStatement (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:17305:8)
    at Parser.pp$8.parseStatement (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:17038:24)
    at Parser.pp$8.parseTopLevel (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:16902:21)
    at Parser.parse (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:16674:15)
    at Function.parse (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:16724:35)
    at Graph.contextParse (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:23090:38)
    at tryParse (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\@rollup\plugin-commonjs\src\parse.js:3:12)
    at analyzeTopLevelStatements (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\@rollup\plugin-commonjs\src\analyze-top-level-statements.js:6:15)
    at Object.transformAndCheckExports (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\@rollup\plugin-commonjs\src\index.js:115:68)
    at Object.transform (C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\@rollup\plugin-commonjs\src\index.js:306:41)
    at C:\Users\jason\Documents\Mendix\MyProject-main\CustomWidgets\reactNativeGiftedChartsLine\node_modules\rollup\dist\shared\rollup.js:22879:40`

**Comment by Abhinandan-Kushwaha** [comment]
Hi @imeidopf 👋
What's the update on this bug, were you able to fix it?

It's not reproducible on my end.

**Comment by imeidopf** [comment]
@Abhinandan-Kushwaha I haven't found a fix for it. I have uploaded the source code for my project. Perhaps you can look there.

https://github.com/imeidopf/Mendix_Widget_GiftedChartsLineChart

**Comment by Abhinandan-Kushwaha** [comment]
Please use the latest version of the library.
